version: "3.1"
services:
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    depends_on:
      - db
  ui:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly:
