version: "3.1"
services:
  ui:
    build: ./webapp
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    networks:
      - db
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  frontend:
    driver: docker-compose-exercise
  db:
    driver: docker-compose-exercise
volumes:
  db:
