version: "3.1"
services:
  app:
    build: ./app
    ports:
      - 5001:5000
    environment:
      DATABASE_URL: “postgresql://flask_user:flask_password@postgres/flask_color_app”
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: flask_color_app
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
    command: /bin/bash -c "psql -h localhost -U flask_user"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

volumes:
  postgres:
