version: "3.1"
services:
  ui:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      MONGODB_INITDB_ROOT_USERNAME: appocation
      MONGODB_INITDB_ROOT_PASSWORD: any_pass
    volumes:
      - /data/db

    depends_on:
      - db
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
