pipeline{
    agent any
    environment{
        IMAGE_NAME='myhttpd'
        VERSION='v1.0.0'
    }
    stages{
        stage("Docker-Verify"){
            steps{
                sh 'docker --version'
            }
        }
        stage("Git-Verify"){
            steps{
                sh 'git --version'
            }
        }
        stage("Docker-Build"){
            steps{
                dir('Labs'){
                    sh 'echo pwd'
                    dir('Task6'){
                        sh 'docker build -t ${IMAGE_NAME}:${VERSION} .' // docker build -t jenbababab:latest --file ./Labs/Task6/Dockerfile .
                    }
                }
            }
        }
    }
}