pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                sh "docker --version"
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "well done"
                }
                failure{
                     echo "ooooops"
                }
            }
        }
        stage("Git-Verify"){
            steps{
                sh "git --version"
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "well done"
                }
                failure{
                     echo "ooooops"
                }
            }
        }
        stage("Docker-Build"){
            steps{
                sh "git --version"
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "well done"
                }
                failure{
                     echo "ooooops"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}